name: Deploy Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # stop previous deploys
  # avoid_redundancy:
  #   runs-on: ubuntu-18.04
  # steps:
  #   - name: Cancel Previous Redundant Builds
  #     uses: styfle/cancel-workflow-action@0.9.1
  #     with:
  #       access_token: ${{ github.token }}

  #  check eslint
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 #default
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload artifact Build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Download Artifact
        uses: actions/download-artifact@4
        with:
          name: dist
          path: dist
      - name: Test
        run: npm test

  e2e:
    needs: [lint, build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: E2E tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000

  # deploy:
  #   needs: [test, e2e]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Deploy to...
  #       if: ${{ github.event_name == 'push' }}
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: ${{secrets.HEROKU_APP}}
  #         heroku_email: ${{secrets.HEROKU_API_EMAIL}}
  #         healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
  #         rollbackonhealthcheckfailed: true
